#!/bin/sh

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	mkd="mkdir -pv" \

# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \

# Allow pritunl to work on linux
alias remove-proxy="unset http_proxy && unset HTTP_PROXY && unset https_proxy && unset HTTPS_PROXY"
alias c4vpn="remove-proxy && pritunl-client-electron </dev/null &> /dev/null &"

alias v="nvim"
alias nv="nvim"
alias sxiv="nsxiv"

alias config='/usr/bin/git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

alias wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"'

# git
alias grbima="git rebase --interactive --autosquash main"

secret () {
  output="${1}".$(date +%s).enc
  gpg --encrypt --armor --output ${output} \
    -r $KEYID "${1}" && echo "${1} -> ${output}"
}

reveal () {
  output=$(echo "${1}" | rev | cut -c16- | rev)
  gpg --decrypt --output ${output} "${1}" && \
    echo "${1} -> ${output}"
}
