#!/bin/zsh

# profile file. Runs on login. Environmental variables are set here.

# If you don't plan on reverting to bash, you can remove the link in ~/.profile
# to clean up.

# pyenv
export PYENV_ROOT="$HOME/.local/src/pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"

# Adds `~/.local/bin` to $PATH
export PATH="$PATH:$HOME/.local/bin"

# Default programs
export EDITOR="nvim"
export TERMINAL="st"
export BROWSER="brave-browser"

# Other program settings
export SUDO_ASKPASS="$HOME/.local/bin/dmenupass"
# Use nvim as man pager
export MANPAGER='nvim +Man!'

# ~/ Clean-up:
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_STATE_HOME="$HOME/.local/state"
export XINITRC="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
export HISTFILE="${XDG_STATE_HOME:-$HOME/.local/state}/zsh/history"
#export XAUTHORITY="$XDG_RUNTIME_DIR/Xauthority" # This line will break some DMs.
export NOTMUCH_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/notmuch-config"
export GTK2_RC_FILES="${XDG_CONFIG_HOME:-$HOME/.config}/gtk-2.0/gtkrc-2.0"
export LESSHISTFILE="-"
export WGETRC="${XDG_CONFIG_HOME:-$HOME/.config}/wget/wgetrc"
export INPUTRC="${XDG_CONFIG_HOME:-$HOME/.config}/shell/inputrc"
export ZDOTDIR="${XDG_CONFIG_HOME:-$HOME/.config}/zsh"
export CARGO_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/cargo"
export RUSTUP_HOME="${XDG_DATA_HOME-$HOME/.local/share}/rustup"
# node
export NPM_CONFIG_USERCONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/npm/npmrc"
export NODE_REPL_HISTORY="${XDG_DATA_HOME-$HOME/.local/share}/node_repl_history"
export N_PREFIX="${XDG_DATA_HOME-$HOME/.local/share}/n"
export PASSWORD_STORE_DIR="${XDG_DATA_HOME-$HOME/.local/share}/gopass"
export GOPATH="${XDG_DATA_HOME-$HOME/.local/share}/go"

export PATH=$GOPATH/bin:/usr/local/go/bin:$HOME/.local/share/npm/bin:$HOME/.local/share/n/bin:$PATH

. $CARGO_HOME/env
